fix gcc and clang build
after upgrading to bison (GNU Bison) 3.8.1 build is broken like this:

build_gcc/sql/sql_yacc.cc:44772:1: error: label ‘yyexhaustedlab’ defined but not used [-Werror=unused-label]
44772 | yyexhaustedlab:
      | ^~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

and:

build/sql/sql_yacc.cc:44772:1: error: unused label 'yyexhaustedlab' [-Werror,-Wunused-label]
yyexhaustedlab:
^~~~~~~~~~~~~~~
1 error generated.

fixing by disabling the diagnostics for sql_yacc.yy