MDEV-19275 : Fix compiler error - calling covention mismatch (32bit Windows)
Error C2440	'initializing': cannot convert from 'MYSQL_RES *(__stdcall *)(MYSQL *)' to 'MYSQL_RES *(__cdecl *)(MYSQL *)'