MDEV-8664 - plugins.show_all_plugins --embedded fails in buildbot
Failed attempt to load dynamic library with STB_GNU_UNIQUE symbol may corrupt
internal dynamic linker data sructures. This looks like libdl bug:
https://sourceware.org/bugzilla/show_bug.cgi?id=14577

In embedded mode "show plugins soname" fails to dlopen ha_mroonga.so (which
has STB_GNU_UNIQUE) due to undefined reference to wsrep_forced_binlog_format.
It crashes later in subsequent call to dlopen() from  pthread_exit().

Disabled plugins.show_all_plugins until dlopen() bug is fixed.