mysql-test-run.pl - fix strict subs in HAVE_WIN32_CONSOLE
Fix mtr error:

Bareword "HAVE_WIN32_CONSOLE" not allowed while "strict subs" in use at mysql-test-run.pl line 387.
Execution of mysql-test-run.pl aborted due to compilation errors.

Added in e3f5789ac0b23a16bb71e06b05dec9cfec3161f0