Bug#14862 undefined reference to `isinf' on SOLARIS - strings/strtod.c  - Rely only on HAVE_ISINF to determine if 'isinf' can be used.
include/my_global.h:
  The test in configure.in determines if we can use "'isinf' after
  having inluded math.h". If the test works HAVE_ISINF will be defined
  and isinf can be used in the code.
  When the configure test fails it's not possible to use 'isinf' only
  by including math.h and thus 'isinf' will be defined to never return
  that X is inifinite.