MDEV-22166 fixup: Undefined reference to WFRM_WRITE_EXTRACTED
It turns out that WFRM_WRITE_EXTRACTED was added only in a debug
assertion and in a comment, as part of
commit b7bba721eee42af892178a747fa72a6fc2975c94.