MDEV-34391 1. Fixed linking failure with undefined reference to the new added    Sql_path::functions during embedded mode compilation. 2. Changes of unit test, path_resolution, modification for the review    point. 3. Fixed path resolution unit test failed with option, --ps-protocol. 4. Added more comments, also including function description. 5. Fixed unit test failed in main.lock_sync 6. The unit test, main.commit_1innodb, the status variable,    Handler_commit, its value incremented due to the the new sql path    resolution mechanism will look for the routine availablity thru    read from the mysql.proc table.
Special thanks to Alexander Barkov <bar@mariadb.com>
https://github.com/MariaDB/server/pull/3566#discussion_r1855892364

Speial thanks to Iqbal Hassan, iqbal-rsec,
https://github.com/MariaDB/server/compare/main...iqbal-rsec:server:
feature/MDEV-13139#
diff-484ece6339a3b31d584d17b98538f692b7f29415be2ec7ec3fdb7c6684204908