MDEV-23496: Fix build issue for MariaDB-10.5 on Debian 9
10.5 fails to build on Debian 9:
"undefined reference to symbol '__bss_start' /usr/lib/x86_64-linux-gnu/libgmp.so.10:
error adding symbols: DSO missing from command line "

The issue was fixed in 10.2 but not merged to 10.5 (MDEV-10943):
Linux does not actually use bss_start;
Put bss_start into #ifndef __linux__ section.

Change-Id: I1aaabc73c2a06071ed4e3eae721fa3701642ee82
Signed-off-by: Yuqi Gu <yuqi.gu@arm.com>