MDEV-30692: conf_to_src incompatible with CHARSET_INFO changes (postfix)
Caused by MDEV-30577 when the CHARSET_INFO structure changed.

As hinted by clang:

error: no member named 'csname' in 'struct charset_info_st'; did you mean 'cs_name'?

Because the target conf_to_src has the properties EXCLUDE_FROM_DEFAULT_BUILD
it hasn't been noticed.

Also correct:

 warning: field precision should have type 'int', but argument has type 'size_t'