RPM: ignore INSTALL_SYSTEMD_{SYSUSERS,TMPFILES}DIR
prevents:
Error: Transaction check error:
  file /usr/lib/sysusers.d from install of MariaDB-server-10.1.31-1.fc27.x86_64 conflicts with file from package systemd-234-9.fc27.x86_64
  file /usr/lib/tmpfiles.d from install of MariaDB-server-10.1.31-1.fc27.x86_64 conflicts with file from package systemd-234-9.fc27.x86_64